### 회원 생성
POST http://localhost:8080/api/v1/member/register
Content-Type: application/json

{
  "username": "gyuyoung",
  "email": "gyuyoung@example.com",
  "age": 28,
  "alias": "규영"
}

### 회원 생성 (alias 없이)
POST http://localhost:8080/api/v1/member/register
Content-Type: application/json

{
  "username": "johndoe",
  "email": "john@example.com",
  "age": 25,
  "alias": null
}

### 이메일로 회원 조회
GET http://localhost:8080/api/v1/member/gyuyoung@example.com
